apiVersion: apps/v1
kind: Deployment
metadata:
  name: cma-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cma
  template:
    metadata:
      labels:
        app: cma
    spec:
      containers:
      - name: cma
        image: de.icr.io/montri-demo/cma:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
